import type { Shot } from './shot';

/**
 * A suggestion generated by the guidance engine.
 */
export interface GuidanceSuggestion {
  /** The type of adjustment suggested */
  action: GuidanceAction;

  /** Human-readable explanation */
  message: string;

  /** Confidence level of the suggestion */
  confidence: 'high' | 'medium' | 'low';

  /** What data points led to this suggestion */
  reasoning: string;
}

/** Possible guidance actions */
export type GuidanceAction = 'grind-finer' | 'grind-coarser' | 'none' | 'experiment';

/**
 * Input data for the guidance engine.
 */
export interface GuidanceInput {
  /** The current shot being evaluated */
  currentShot: Shot;

  /** Previous shot for comparison (optional) */
  previousShot: Shot | null;

  /** Target parameters if known (optional) */
  target?: GuidanceTarget;
}

/**
 * Optional target parameters for guidance.
 */
export interface GuidanceTarget {
  ratio?: number;
  timeSecondsMin?: number;
  timeSecondsMax?: number;
}
